### ISSUE TITLE
输入框的文字不能翻译

### ISSUE THREAD

**Issue by TaylorBoy** [jtaox/chrome-extension-translatorX#1]
有时候需要翻译的内容, 鼠标点击后, 直接变成可编辑的文本输入框, 这时候不能翻译, 比较不方便.
可以优化一下吗, 或者在扩展的图标上增加一个输入框, 可以粘贴并翻译.

`Chromium 版本 71.0.3578.98（正式版本）Built on Ubuntu , running on Ubuntu 16.04 （64 位）`

**Comment by jtaox** [comment]
感谢，会抽空优化
