### ISSUE TITLE
只能翻译单行文本

### ISSUE THREAD

**Issue by heyzqq** [jtaox/chrome-extension-translatorX#2]
翻译英文多行时, 只能返回第一行, 后面的自动忽略了, 英文大都比较长, 很容易出现分行的现象.  

像这篇博客 (http://squidarth.com/rc/programming/networking/2018/07/18/intro-congestion.html) 就特别明显.

感谢你的作品,
期待优化!

**Comment by jtaox** [comment]
感谢建议，chrome73也禁止了扩展的content script跨域请求，抽时间统一优化
