### ISSUE TITLE
[建议] 显示结果框会挡住鼠标

### ISSUE THREAD

**Issue by heyzqq** [jtaox/chrome-extension-translatorX#3]
背景: 有些页面比较不友好, 从第一个字符划词容易全部选中, 所以我习惯双击选中单词再划完整句话.  

这样做, 会出现一个问题, 双击选中单词后, 鼠标还没松开, 翻译结果已经出来了, 要往下翻译的时候, 划到翻译结果就会选中后面全部的内容.

**建议: 松开鼠标之后, 再显示翻译结果.**

Thanks!

**Comment by jtaox** [comment]
当时想着没人用，写的比较随意，很多细节和UI有欠缺😆。感谢建议，我会进行调整。
